name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: energy_analytics
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U admin -d energy_analytics"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create local config for CI
        run: |
          cat <<EOF > config.yaml
          database:
            host: 127.0.0.1
            port: 5432
            dbname: energy_analytics
            user: admin
            password: password
          EOF


      - name: Initialize Database Schema
        run: |
          python src/setup_db.py

      - name: Generate Scaled-Down CI Data
        run: |
          python src/generate_data.py --rows 50000

      - name: Ingest Data into PostgreSQL
        run: |
          python src/ingest.py

      - name: Run Data Quality Checks
        run: |
          python src/run_quality_checks.py

      - name: Run Pytest Suite
        env:
          CI: "true"
        run: |
          pytest tests/ -v
